ALICE_HOST_TIME := $(shell date +"%Y%m%d-%H%M")

ifndef ALICE_BUILD_TYPE
   ALICE_BUILD_TYPE := UNOFFICIAL
endif

ALICE_VERSION := Maze
XDROID_BUILD_VERSION := alice$(ALICE_VERSION)-$(ALICE_BUILD)-$(ALICE_HOST_TIME)-$(ALICE_BUILD_TYPE)
XDROID_BUILD_NUMBER := alice.$(ALICE_VERSION).$(ALICE_HOST_TIME)

PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
   ro.alice.version=$(ALICE_VERSION) \
   ro.alice.build.version=$(ALICE_BUILD_VERSION) \
   ro.alice.build.number=$(ALICE_BUILD_NUMBER) \
   ro.alice.build.type=$(ALICE_BUILD_TYPE))
